version: '3'

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: person
  keycloak:
    image: bitnami/keycloak:26
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_DATABASE_VENDOR: dev-file