env: local

datasource:
  host: "localhost"
  port: 5432
  user: postgres
  password: postgres
  db-name: postgres

cors:
  allowed-origins:
    - "*"
  max-age: 3600

server:
  port: 9902
  timeout: 4s
  idle-timeout: 60s